### ISSUE TITLE
RuntimeError: Numpy is not available

### ISSUE THREAD

**Issue by tiancpeng** [tianrun-chen/xLSTM-UNet-PyTorch#2]
numpy                     2.0.0                    pypi_0    pypi
Why is there no numpy package？

**Comment by tiancpeng** [comment]
2024-07-08 15:35:06.339380: Epoch 0
2024-07-08 15:35:06.339683: Current learning rate: 0.001
Traceback (most recent call last):
  File "/public/home/xukai_tcp_2607/.conda/envs/uxlstm/bin/nnUNetv2_train", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
  File "/public/home/xukai_tcp_2607/xLSTM-UNet-PyTorch-main/UxLSTM/nnunetv2/run/run_training.py", line 274, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/public/home/xukai_tcp_2607/xLSTM-UNet-PyTorch-main/UxLSTM/nnunetv2/run/run_training.py", line 208, in run_training
    nnunet_trainer.run_training()
  File "/public/home/xukai_tcp_2607/xLSTM-UNet-PyTorch-main/UxLSTM/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1262, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/public/home/xukai_tcp_2607/.conda/envs/uxlstm/lib/python3.10/site-packages/batchgenerators/dataloading/single_threaded_augmenter.py", line 38, in __next__
    item = self.transform(**item)
  File "/public/home/xukai_tcp_2607/.conda/envs/uxlstm/lib/python3.10/site-packages/batchgenerators/transforms/abstract_transforms.py", line 88, in __call__
    data_dict = t(**data_dict)
  File "/public/home/xukai_tcp_2607/.conda/envs/uxlstm/lib/python3.10/site-packages/batchgenerators/transforms/utility_transforms.py", line 65, in __call__
    data_dict[key] = self.cast(torch.from_numpy(data_dict[key])).contiguous()
RuntimeError: Numpy is not available

**Comment by JSJ666** [comment]
I encountered the same problem. Have you found a solution?

**Comment by schoreD** [comment]
> numpy 2.0.0 pypi_0 pypi Why is there no numpy package？为什么没有numpy包？

请问您的数据集的josn文件在哪里下载的？提供的数据集不全？

**Comment by schoreD** [comment]
> I encountered the same problem. Have you found a solution?我遇到了同样的问题。你找到解决办法了吗？
你好 请问你的数据集的josn文件怎么下载的

**Comment by JSJ666** [comment]
The dataset contains JSON files.

**Comment by JSJ666** [comment]
> > I encountered the same problem. Have you found a solution?我遇到了同样的问题。你找到解决办法了吗？
> > 你好 请问你的数据集的josn文件怎么下载的

The dataset contains JSON files.

**Comment by chord1412077** [comment]
> > numpy 2.0.0 pypi_0 pypi Why is there no numpy package？为什么没有numpy包？
> 
> 请问您的数据集的josn文件在哪里下载的？提供的数据集不全？

用这个命令来对数据集进行预处理，获取json文件：
nnUNetv2_plan_and_preprocess -d DATASET_ID --verify_dataset_integrity

**Comment by chord1412077** [comment]
> I encountered the same problem. Have you found a solution?

use numpy==1.26.3
trust me，it will done！

**Comment by chord1412077** [comment]
> use numpy==1.26.3
> trust me，it will done！



> numpy 2.0.0 pypi_0 pypi Why is there no numpy package？

use numpy==1.26.3
trust me，it will done！
